version: '3.8'

services:
  order-consumer:
    build:
      context: .
      dockerfile: ./order-consumer/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env

  order-producer:
    build:
      context: .
      dockerfile: ./order-producer/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - order-consumer